services:
   mariadb:
     image: mariadb:latest
     container_name: dev-mariadb
     restart: always
     ports:
       - 3316:3306
     environment:
       TZ: Asia/Seoul
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_USER: admin
       MYSQL_PASSWORD: admin
     command:
       - --character-set-server=utf8mb4
       - --collation-server=utf8mb4_unicode_ci
       - --skip-character-set-client-handshake
     volumes:
       - ./dev-mariadb/data:/var/lib/mysql